# HW 1 Warm Up
#### Hunter Lybbert
#### Student ID 2426454
#### 09-27-24

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import newton, bisect

In [2]:
def my_bisection_method(
    func: callable,
    a: float,
    b: float,
    tol: float = 1e-6,
    max_iter: int = 100,
) -> tuple[float, int, np.array]:
    """
    The basic bisection method for root finding.

    returns the tuple of the root, the number of iterations, and the midpoint values from throughout

    """
    x_mids = []

    for i in range(0, max_iter):
        x_current = (b + a)/2
        x_mids.append(x_current)
        f_current = func(x_current)
        if ( f_current > 0 ):
            a = x_current
        else:
            b = x_current
        if ( abs(f_current) < tol ):
            break

    return (x_current, len(x_mids), np.array(x_mids))


def my_newton_raphson_method(
    func: callable,
    func_prime: callable,
    x: float,
    tol: float = 1e-6,
    max_iter: int = 1000,
) -> tuple[float, int, np.array]:
    """
    The basic newton raphson method for root finding.

    returns the tuple of the root, the number of iterations, and the values of x along the way
    """
    x_prev = x
    x_guesses = [x_prev]

    for i in range(max_iter):
        
        x_current = (
            x_prev - func(x_prev)/func_prime(x_prev)
        )
        x_prev = x_current
        x_guesses.append(x_current)
        f_current = func(x_current)
        if abs(f_current) < tol:
            break


    return (x_current, len(x_guesses), np.array(x_guesses))


In [3]:
# Here are some test functions
# test_func = lambda x: np.exp(x) - np.tan(x)
# test_func_prime = lambda x: np.exp(x) - 1 / np.cos(x)**2

# my_bisection_method(test_func, a=-4, b=-2.8, tol=1e-5)
# my_newton_raphson_method(func=test_func, func_prime=test_func_prime, x=-4, tol=1e-5)

## Part I

In [4]:
def func(x: float) -> float:
    """The function we are trying to approximate today"""
    return x*np.sin(3*x) - np.exp(x)

def func_prime(x: float) -> float:
    """The derivative of `func` so we can use newtons method"""
    return np.sin(3*x) + 3*x*np.cos(3*x) - np.exp(x)

In [5]:
res_newton = newton(
    func=func,
    x0=-1.6,
    full_output=True,
    tol=1e-6
)

In [6]:
res_newton

(np.float64(-2.1134609842346768),
       converged: True
            flag: converged
  function_calls: 8
      iterations: 7
            root: -2.1134609842346768
          method: secant)

In [7]:
my_res_newton = my_newton_raphson_method(func=func, func_prime=func_prime, x=-1.6)

In [8]:
my_res_newton

(np.float64(-0.57078961788788),
 11,
 array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
        -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
        -0.57078962]))

In [9]:
res_bisect = bisect(
    f=func,
    a=-0.7,
    b=-0.4,
    full_output=True,
    xtol=1e-6,
)

In [10]:
res_bisect

(-0.5707899093627932,
       converged: True
            flag: converged
  function_calls: 21
      iterations: 19
            root: -0.5707899093627932
          method: bisect)

In [11]:
my_res_bisect = my_bisection_method(
    func=func,
    a=-0.7,
    b=-0.4,
)

In [12]:
my_res_bisect

(-0.5707893371582031,
 17,
 array([-0.55      , -0.625     , -0.5875    , -0.56875   , -0.578125  ,
        -0.5734375 , -0.57109375, -0.56992188, -0.57050781, -0.57080078,
        -0.5706543 , -0.57072754, -0.57076416, -0.57078247, -0.57079163,
        -0.57078705, -0.57078934]))

In [13]:
# A1 is the vector of x-values in the Newton method starting with the initial guess x(1) = -1.6
A1 = my_res_newton[-1]
# A2 is the midpoint x_mid values in the bisection method for successive iterations
A2 = my_res_bisect[-1]
# A3 is a 1x2 vector with number of iterations for the Newton and bisection methods respectively as the two components
A3 = np.array([my_res_newton[1], my_res_bisect[1]])

In [14]:
A1

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962])

In [15]:
A2

array([-0.55      , -0.625     , -0.5875    , -0.56875   , -0.578125  ,
       -0.5734375 , -0.57109375, -0.56992188, -0.57050781, -0.57080078,
       -0.5706543 , -0.57072754, -0.57076416, -0.57078247, -0.57079163,
       -0.57078705, -0.57078934])

In [16]:
A3

array([11, 17])

## Part II

In [17]:
A = np.array([
    [ 1, 2],
    [-1, 1],
])
B = np.array([
    [2, 0],
    [0, 2],
])
C = np.array([
    [2, 0, -3],
    [0, 0, -1],
])
D = np.array([
    [1, 2],
    [2, 3],
    [-1, 0],
])
x = np.array([1, 0])
y = np.array([0, 1])
z = np.array([1, 2, -1])

In [18]:
A4 = A + B

In [19]:
A5 = 3*x - 4*y

In [20]:
A6 = A@x

In [21]:
A7 = B@(x - y)

In [22]:
A8 = D@x

In [23]:
A9 = D@y + z

In [24]:
A10 = A@B

In [25]:
A11 = B@C

In [26]:
A12 = C@D