## Calculate Eigenvalues

In [3]:
import numpy as np

A = np.array([[.5, .25], [.5, -.125]])

eige_vals, eig_vecs = np.linalg.eig(A)
eige_vals

array([ 0.65936465, -0.28436465])

In [4]:
eig_vecs

array([[ 0.84324302, -0.3036773 ],
       [ 0.53753252,  0.95277495]])

In [15]:
# Esnsure which eigenvalue corresponds to which eigenvector
tol = 1e-16
assert (A@eig_vecs[:,0] - eige_vals[0]*eig_vecs[:,0] < tol).all()
assert (A@eig_vecs[:,1] - eige_vals[1]*eig_vecs[:,1] < tol).all()

In [18]:
x = np.array([1, 1])
x_hat = x / np.linalg.norm(x)

y = A@x
y_hat = y / np.linalg.norm(y)

x_hat, y_hat

(array([0.70710678, 0.70710678]), array([0.89442719, 0.4472136 ]))